name = "CausalTools"
uuid = "a5c30464-85d3-4c83-883b-b6a788ccfc6f"
authors = ["Elia Gonzato"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
CSV = "0.10.15"
Colors = "0.13.1"
DataFrames = "1.8.0"
Documenter = "1.14.1"
GLM = "1.9.0"
IterTools = "1.10.0"
Logging = "1.11.0"
Plots = "1.41.1"
Revise = "3.9.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
StatsModels = "0.7.7"
StatsPlots = "0.15.8"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
